# Generated by Django 3.2.4 on 2021-07-03 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_entry_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='item',
        ),
    ]
