# Generated by Django 3.2.4 on 2021-07-12 23:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_remove_entry_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='entry',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='entry',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
