# Generated by Django 3.2.4 on 2021-08-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_entry_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='category',
            field=models.CharField(choices=[('Groceries', 'Groceries'), ('Dinning & Drinks', 'Dinning and Drinks'), ('Uncategorized', 'Uncategorized'), ('Charity', 'Charity'), ('Education', 'Education'), ('Entertainment', 'Entertainment'), ('Fees & Charges', 'Fees & Charges'), ('Financial', 'Financial'), ('Fitness', 'Fitness'), ('Gifts', 'Gifts'), ('Health', 'Health'), ('Loans', 'Loans'), ('Pets', 'Pets'), ('Shopping', 'Shopping'), ('Taxes', 'Taxes'), ('Travel', 'Travel'), ('Utilities', 'Utilities'), ('Auto & Transport', 'Auto & Transport')], default='Uncategorized', max_length=250),
        ),
    ]
