# Generated by Django 4.0.4 on 2022-05-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_alter_entry_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
    ]
